"""Abstract STATE families for Ragnarok shape distillation.

These are generators for impossible worlds. They are not SWC classes,
not scanner categories, and not names to copy onto a CX card.

Cues match source-finding language (including words we refuse to emit).
Output fields stay in state language: two representations of a fact,
valid actions, an assertable witness.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Family:
    fid: str
    name: str
    fact_a: str
    fact_b: str
    construction: str
    witness: str
    monetize_kill: str
    cues: tuple[str, ...]
    seams_hint: tuple[str, ...]


# Cue patterns are searched against title+description+poc (case-insensitive).
FAMILIES: tuple[Family, ...] = (
    Family(
        fid="claims_vs_assets",
        name="Claims stay constant while redeemable assets fall",
        fact_a="claim / share / ticket ledger",
        fact_b="custody token / redeemable backing",
        construction="A permissionless actor moves backing out along a path that does not burn matching claims, or burns claims without releasing backing. Each call returns success.",
        witness="claimSupply unchanged AND custodyBalance down (or inverse) AND last call success",
        monetize_kill="Redeem or liquidate the leftover claim. Dies if burn and release are one atomic conservation write.",
        cues=(
            r"totalassets|converttoshares|convertoassets|share price|shareprice",
            r"vault.*(withdraw|donate|harvest)|donate.*vault",
            r"redeemable|backing.*(decrease|drain)|assets? (decrease|stolen|drained)",
        ),
        seams_hint=("vault", "accounting"),
    ),
    Family(
        fid="right_a_redeem_b",
        name="Right acquired in state A redeemed in state B",
        fact_a="parameters / epoch / config at mint",
        fact_b="parameters / epoch / config at redeem",
        construction="Mint or queue a right under one config, then change oracle, cap, epoch, or backing and redeem under the new world.",
        witness="right.paramsEpoch != settle.paramsEpoch AND settle succeeds",
        monetize_kill="The delta between mint-world and redeem-world is extractable. Dies if the ticket stores and enforces its mint-world parameters.",
        cues=(
            r"mint(ed)? under.{0,60}redeem",
            r"redeem.{0,40}(after|under) (a )?(new|updated|changed|later)",
            r"ticket.{0,30}(epoch|param).{0,30}settle",
            r"queue.{0,40}(later|after).{0,40}(redeem|settle)",
            r"acquired in state .{0,10}redeem",
        ),
        seams_hint=("payments", "vault"),
    ),
    Family(
        fid="auth_a_exec_b",
        name="Authorization in A, execution in B",
        fact_a="identity / nonce / context that passed the check",
        fact_b="identity / nonce / context that received the write",
        construction="Pass a check against one caller, signature, or allowance, then land the value movement on a different subject.",
        witness="auth.context != execution.context AND value moved",
        monetize_kill="The unauthorized subject keeps the value. Dies if the execution binds the same bytes the check hashed.",
        cues=(
            r"on behalf|without (having )?any allowance|msg\.sender",
            r"authorization|missing validation|does not (check|validate) (the )?(caller|sender|owner)",
            r"arbitrary (from|owner|recipient)",
        ),
        seams_hint=("privilege", "payments"),
    ),
    Family(
        fid="two_ledgers",
        name="Two ledgers of the same fact disagree after every call returns success",
        fact_a="component A record of the fact",
        fact_b="component B record of the same fact",
        construction="A sequence of valid calls updates one ledger and not the other. No function reverts.",
        witness="reprA != reprB AND last call success",
        monetize_kill="Settle against the more favorable ledger. Dies if a single conservation identity is written in both places.",
        cues=(
            r"inconsistent|desynchron|out of sync|mismatch(ed)? (balanc|account|share|debt)",
            r"accounting (error|discrep|bug)|double.?count",
        ),
        seams_hint=("accounting",),
    ),
    Family(
        fid="entitlement_no_payment",
        name="Entitlement exists without a corresponding payment obligation",
        fact_a="live claim / ticket / share",
        fact_b="recorded obligation / escrow / backing",
        construction="Mint or transfer a claim along a path that never books who owes the backing.",
        witness="claim.balanceOf(user) > 0 AND escrow.owed == 0",
        monetize_kill="Redeem the unbacked claim. Dies if minting the claim always increments the obligation in the same call.",
        cues=(
            r"unbacked|unbacked mint|no collateral|without (depositing|locking|paying)",
            r"mint.*(free|without)|claim.*(without|no) (debt|obligation|escrow)",
        ),
        seams_hint=("vault", "stablecoin", "payments"),
    ),
    Family(
        fid="payment_no_entitlement",
        name="Payment obligation exists without a remaining entitlement",
        fact_a="payout / release path still live",
        fact_b="claim already burned or assigned away",
        construction="Burn, transfer, or cancel the claim, then still take the payout path.",
        witness="claim burned AND payout path still transferable",
        monetize_kill="Collect the second payout. Dies if payout burns the same id it releases.",
        cues=(
            r"already (burned|claimed|withdrawn)|withdraw.*(after|twice)",
            r"release without burn|pay(ment)? after (burn|cancel)",
        ),
        seams_hint=("payments", "vault"),
    ),
    Family(
        fid="identity_vs_recipient",
        name="Identity that passed a check is not the identity that receives value",
        fact_a="address that satisfied the predicate",
        fact_b="address that is paid or credited",
        construction="Satisfy a signature, merkle proof, or owner check, then set recipient / token / handler to an attacker-controlled address.",
        witness="payer != recipient relative to the check that passed AND value moved",
        monetize_kill="Attacker receives the transfer. Dies if recipient is bound into the checked digest.",
        cues=(
            r"recipient|beneficiary|to address|wrong (owner|recipient)",
            r"hijack|setFallbackHandler|arbitrary token|stolen.*(nft|erc20|funds)",
        ),
        seams_hint=("payments", "nft", "privilege"),
    ),
    Family(
        fid="price_vs_solvency",
        name="Price used to create a position is not the price that keeps the system solvent",
        fact_a="mark used to mint / borrow / open",
        fact_b="mark used to liquidate / redeem / settle",
        construction="Open a position against one feed or spot, then settle against a different feed, a stale round, or a mark the opener can push.",
        witness="mintPrice != solvencyPrice AND position created AND later settle succeeds",
        monetize_kill="Extract the wedge between the two marks. Dies if both paths read the same bounded feed with the same heartbeat.",
        cues=(
            r"oracle|chainlink|twap|price feed|stale (price|round)",
            r"spot price|price manip|incorrect price|wrong price",
            r"liquida.*(price|oracle)|mint.*(oracle|price)",
        ),
        seams_hint=("oracle", "lending", "stablecoin"),
    ),
    Family(
        fid="recorded_vs_transferable",
        name="Recorded balance exceeds transferable balance",
        fact_a="internal accounting balance",
        fact_b="token.balanceOf(this) / native backing",
        construction="Credit an internal ledger from a donation, rebase, or failed transfer that does not actually move tokens in.",
        witness="internalBal > token.balanceOf(this)",
        monetize_kill="Withdraw the recorded amount until custody is empty; later users are short. Dies if credits are `min(internal, actual)` at payout.",
        cues=(
            r"balanceof\(address\(this\)\)|internal (balance|account)|cached balance",
            r"fee.?on.?transfer|rebase|transfer returned false",
        ),
        seams_hint=("vault", "accounting"),
    ),
    Family(
        fid="queue_transfer_backing",
        name="A queued claim is transferable into a different backing or settlement state",
        fact_a="ticket at issuance",
        fact_b="backing / oracle / config at settlement",
        construction="Enter a queue or vest, transfer the ticket, then settle after backing, oracle, or cap changed.",
        witness="ticket.owner changed AND backingEpoch changed AND redeem succeeds",
        monetize_kill="The new owner redeems under richer backing. Dies if the ticket snapshots backing and settlement honors the snapshot.",
        cues=(
            r"queue|pending (redeem|withdraw)|vesting.*(transfer|sell)",
            r"transfer.*(position|ticket|receipt)|position token",
        ),
        seams_hint=("payments", "vault", "stablecoin"),
    ),
    Family(
        fid="fast_vs_slow",
        name="Fast path updates a subset of the state the slow path updates",
        fact_a="short-circuit writes",
        fact_b="full-path conservation writes",
        construction="Take the helper / cache / multiHop / zap path that skips a write the canonical path uses as conservation.",
        witness="after fast path, slow-path storage field unchanged AND value moved",
        monetize_kill="The skipped write is the one that would have billed the attacker. Dies if both paths share one internal settle.",
        cues=(
            r"multihop|shortcut|cache(d)? (reser|balanc)|fast path",
            r"skips? (the )?(update|write|check)|does not update",
        ),
        seams_hint=("vault", "payments", "lending"),
    ),
    Family(
        fid="burn_without_release",
        name="Burn without matching release, or release without matching burn",
        fact_a="token burn / lock",
        fact_b="collateral release / mint",
        construction="Trigger one side of a two-sided conservation law without the other.",
        witness="burned > 0 AND released == 0 (or the reverse) in the same sequence",
        monetize_kill="Keep both the claim and the backing, or neither. Dies if burn and release share one non-reentrant conservation function.",
        cues=(
            r"burn.*(without|but not)|without (burning|releasing|locking)",
            r"unlock without|mint without lock|lock without mint",
        ),
        seams_hint=("stablecoin", "bridge", "vault"),
    ),
    Family(
        fid="message_without_lock",
        name="Message or receipt accepted on one side without the lock or burn on the other",
        fact_a="message / receipt / validator signature on destination",
        fact_b="lock / burn / escrow on source",
        construction="Replay, forge, or reorder a message so destination mints or unlocks while source never committed.",
        witness="mint/unlock succeeded AND lock/burn on source is absent",
        monetize_kill="Minted destination assets are sold. Dies if destination verifies a source commitment that cannot be replayed.",
        cues=(
            r"bridge|layerzero|\blz\b|anycall|cross.?chain|message passing",
            r"replay|lock.?mint|unlock without|mint without.*(lock|burn)",
        ),
        seams_hint=("bridge",),
    ),
    Family(
        fid="one_shot_twice",
        name="A one-shot right can be consumed twice across two adapters",
        fact_a="consumed receipt on adapter A",
        fact_b="still-live receipt on adapter B / legacy path",
        construction="Settle once through the new door, again through the old door (or two tokens, two chains, two entrypoints).",
        witness="two successful value-outs for one burned-in",
        monetize_kill="Double settlement. Dies if one spent-id namespace is shared.",
        cues=(
            r"double (spend|claim|withdraw|settle)|claimed twice|twice",
            r"replay.*(sig|message|permit|nonce)|nonce.*reuse",
        ),
        seams_hint=("payments", "bridge", "signature"),
    ),
    Family(
        fid="harvest_wrong_ledger",
        name="Yield or harvest credits a ledger that cannot be the depositor's claim",
        fact_a="harvest / reward / leftover accounting",
        fact_b="share / convertToAssets claim",
        construction="Call harvest, notify, or distribute so value lands in a leftover, fee, or unseen-reward bucket that redeem does not follow.",
        witness="harvest increased leftover AND convertToAssets(shares) did not",
        monetize_kill="Claim the leftover via the sibling path. Dies if harvest mints shares or raises convertToAssets for holders.",
        cues=(
            r"harvest|notifyreward|getreward|unseenreward|fee distribution",
            r"reward.*(index|per.?token)|compound.*yield",
        ),
        seams_hint=("vault", "staking"),
    ),
    Family(
        fid="pause_sibling_open",
        name="Pause or kill-switch blocks the documented path but not a value-moving sibling",
        fact_a="paused / guardian flag",
        fact_b="sibling entry that still moves claims or assets",
        construction="Set or observe paused=true, then call harvest, donate, settle, or a legacy entry.",
        witness="paused() == true AND sibling call moved value",
        monetize_kill="Value leaves during the emergency. Dies if every value-moving entry reads the same flag first.",
        cues=(
            r"\bpause|\bpaused\b|kill.?switch|guardian",
            r"still (callable|works)|bypass.*pause|pause.*(not|doesn't|does not)",
        ),
        seams_hint=("privilege",),
    ),
    Family(
        fid="flag_closed_write_open",
        name="Flag says closed while a write path still treats the surface as open",
        fact_a="initializer / migrated / disabled storage",
        fact_b="write entry that still succeeds",
        construction="After initialize, migrate, or sunset, call the forbidden write (re-init, old mint, old settle).",
        witness="initialized == true (or migrated == true) AND the forbidden write succeeded",
        monetize_kill="Re-init as owner or mint under old math. Dies if the flag gates every write, including inherited ones.",
        cues=(
            r"initializ|reinit|migrate|sunset|disabled",
            r"already initialized|initializer.*(missing|bypass)|proxy.*init",
        ),
        seams_hint=("privilege",),
    ),
    Family(
        fid="supply_backing_inverse",
        name="Supply and backing move in opposite directions on a conservation-neutral user action",
        fact_a="totalSupply / shares",
        fact_b="totalAssets / collateral",
        construction="A deposit, withdraw, or harvest that should be value-neutral mints claims or leaks backing.",
        witness="user action AND totalSupply up AND totalAssets down (or inverse)",
        monetize_kill="Inflated shares redeem more than deposited. Dies if the action writes both sides with the same amount.",
        cues=(
            r"inflation|share.*inflate|totalSupply.*(increase|mint)",
            r"exchange.?rate|price.?per.?share",
        ),
        seams_hint=("vault", "accounting"),
    ),
    Family(
        fid="check_then_invalidate",
        name="A check's meaning is invalidated between pass and settlement",
        fact_a="predicate snapshot at check",
        fact_b="predicate at value movement",
        construction="Pass a balance, allowance, health, or uniqueness check, then (same transaction or next) change the world before settlement via callback, hook, or later call.",
        witness="check-time snapshot != settle-time snapshot AND settle succeeded",
        monetize_kill="Settlement honors a predicate that is no longer true. Dies if settlement re-reads and re-checks the same storage.",
        cues=(
            r"callback|onERC|reentran|checks.?effects|read.?only.?reentran",
            r"hook.*(before|after)|between.*check.*settlement",
            r"state.*(after|before) the call",
        ),
        seams_hint=("callback", "payments"),
    ),
    Family(
        fid="empty_rate",
        name="Empty, dust, or first-actor rate lets the next actor's claim dominate",
        fact_a="near-zero denominator / first shares",
        fact_b="subsequent minter's claim on real assets",
        construction="Donate, withdraw to dust, or be first depositor so convertToShares becomes extreme, then mint cheaply against donated backing.",
        witness="convertToShares(1) extreme AND attackerShares / totalShares high",
        monetize_kill="Attacker owns almost all redeemable assets. Dies if virtual shares/assets floor the rate, or first deposit is seeded.",
        cues=(
            r"first deposit|inflation attack|empty vault|dead shares",
            r"donation attack|donate.*(mint|share)|dust.*share",
        ),
        seams_hint=("vault",),
    ),
    Family(
        fid="unsolicited_transfer_rate",
        name="An unsolicited transfer changes a rate used by a later mint without minting shares",
        fact_a="totalAssets after raw transfer",
        fact_b="totalSupply unchanged",
        construction="Transfer tokens directly to the vault/pool, then mint at the new rate.",
        witness="totalAssets up with totalSupply unchanged, then mint cheaper than before",
        monetize_kill="Next minter is diluted or the donor extracts via a sandwich mint. Dies if donations mint shares or are excluded from the rate.",
        cues=(
            r"direct(ly)? send|direct transfer|unsolicited|donate",
            r"balanceof.*totalassets|next (user|deposit).*share",
        ),
        seams_hint=("vault", "amm"),
    ),
    Family(
        fid="same_tx_mark",
        name="Liquidation or redemption uses a mark a same-tx actor can move",
        fact_a="spot / reserve / tick the actor just pushed",
        fact_b="liquidation / redeem / mint using that mark",
        construction="Move a thin pool or manipulate a readable reserve, then liquidate or redeem in the same transaction.",
        witness="attacker-moved reserve AND liquidation using that reserve in the same tx",
        monetize_kill="Seize collateral or mint against the pushed mark. Dies if the mark is a bounded TWAP or an external heartbeat feed.",
        cues=(
            r"flash.?loan|same (tx|transaction)|spot.*(liquida|redeem)",
            r"manipulat.*(reserv|price|spot)|thin (pool|market)",
        ),
        seams_hint=("oracle", "amm", "lending"),
    ),
    Family(
        fid="peripheral_setter",
        name="A role that looks view-only writes a parameter that reprices claims",
        fact_a="peripheral / keeper / strategy setter",
        fact_b="core rate / whitelist / oracle used at redeem",
        construction="Call a 'helper' setter that is permissionless or weakly gated, then redeem or liquidate on the new number.",
        witness="non-admin call changed rate/whitelist AND redeem uses the new number",
        monetize_kill="Attacker reprices everyone else's claims. Dies if the setter is admin-only and out of bounty scope (then CLASS PRIVILEGED, not EXTRACT).",
        cues=(
            r"anyone can (set|call|update)|missing (onlyowner|access)|public setter",
            r"keeper.*(set|update)|strategy.*(set|migrate)|whitelist",
        ),
        seams_hint=("privilege", "oracle"),
    ),
    Family(
        fid="legacy_after_migration",
        name="Legacy path still ACTIVE after new accounting took over",
        fact_a="v1 entry still callable",
        fact_b="v2 ledger / assumption",
        construction="After migration, call the old mint, settle, or withdraw that still writes value under v2's assumptions.",
        witness="v1 call succeeded AND v2 conservation broken",
        monetize_kill="Old math against new backing. Dies if v1 is bricked (selfdestruct, flag, or removed selector) on the live deployment.",
        cues=(
            r"legacy|old (function|contract|version)|v1.*(still|after)",
            r"migrat.*(still|old)|deprecated.*(callable|still)",
        ),
        seams_hint=("privilege", "vault"),
    ),
    Family(
        fid="replay_after_change",
        name="Same intent settled twice after validator, implementation, or config change",
        fact_a="spent receipt under old impl / signer set",
        fact_b="live receipt under new impl / signer set",
        construction="Consume a message, upgrade or rotate validators, then settle the same intent again.",
        witness="second settle/mint succeeded for the same intent id",
        monetize_kill="Replay across the upgrade. Dies if spent-ids live in a storage contract that survives the upgrade.",
        cues=(
            r"upgrade.*(replay|message)|after upgrade|new implementation",
            r"validator.*(change|set)|signer.*(change|rotate)",
        ),
        seams_hint=("bridge", "privilege", "signature"),
    ),
    Family(
        fid="partial_fill_zero",
        name="Partial fill or settle deletes the full remaining entitlement",
        fact_a="amount actually paid",
        fact_b="remaining ticket / allowance / order",
        construction="Pay some of a claim; observe the rest zeroed, or fill against an order that deletes sibling amounts.",
        witness="paid < owed AND remaining claim == 0",
        monetize_kill="The unpaid remainder is stolen or unredeemable. Dies if remaining is decremented by paid, not zeroed.",
        cues=(
            r"partial (fill|settle|withdraw|claim)|remaining.*(zero|delet)",
            r"entire (order|position|allowance).*(cancel|clear|zero)",
        ),
        seams_hint=("payments", "amm"),
    ),
    Family(
        fid="refund_wrong",
        name="Refund or cancel does not restore the original claim, or restores it twice",
        fact_a="original claim / escrow",
        fact_b="post-unwind claim / escrow",
        construction="Cancel, abort, or refund a filled or partially filled action.",
        witness="after unwind, claim != original by more than fees (duplicate or zero)",
        monetize_kill="Duplicate claim is redeemed, or the user is zeroed and the leftover sits in the contract. Dies if unwind is the inverse of the original writes.",
        cues=(
            r"refund|cancel order|abort|unwind",
            r"does not restore|restores? twice|duplicate claim",
        ),
        seams_hint=("payments",),
    ),
    Family(
        fid="local_ok_joint_unbacked",
        name="Two components each locally conservative, jointly creating unbacked claims",
        fact_a="invariant of component A",
        fact_b="invariant of component B",
        construction="Drive A and B through internally-legal calls whose composition mints value from nowhere.",
        witness="A.ok AND B.ok AND systemClaims > systemAssets",
        monetize_kill="Redeem the joint surplus. Dies if a system-level conservation identity is checked at the seam.",
        cues=(
            r"compos(e|ition)|across (two|both) (contract|module)|between .* and",
            r"each .* correct|locally (correct|conservative)",
        ),
        seams_hint=("accounting", "callback"),
    ),
    Family(
        fid="epoch_boundary",
        name="Time or epoch boundary where a right survives into the next epoch's parameters",
        fact_a="right.epoch",
        fact_b="execution epoch rates / oracles / caps",
        construction="Acquire a right just before an epoch, round, or funding event; execute just after.",
        witness="right.epoch < exec.epoch AND exec uses exec.epoch parameters",
        monetize_kill="Capture the parameter jump. Dies if execution uses the stored epoch's parameters.",
        cues=(
            r"epoch|funding (rate|time)|round id|period boundary",
            r"after (the )?(update|window|expiry)|before.*(update|window)",
        ),
        seams_hint=("oracle", "payments", "lending"),
    ),
    Family(
        fid="keeper_race",
        name="Keeper or permissioned settle that a permissionless actor can force-order to capture value",
        fact_a="keeper / solver / cranker expected order",
        fact_b="permissionless sandwich or same-tx top",
        construction="Observe a profitable keeper action and wrap it atomically, or prevent it until a private order lands.",
        witness="same-tx ordering captures value that a delayed keeper would have denied",
        monetize_kill="MEV on the settle. Dies if the profit requires a privileged key the program treats as trusted (then PRIVILEGED/GRIEF, not EXTRACT).",
        cues=(
            r"keeper|crank|harvester|solver|front.?run|sandwich",
            r"mev|force.?order|permissionless.*(liquida|harvest|settle)",
        ),
        seams_hint=("payments", "privilege", "lending"),
    ),
    Family(
        fid="signature_context",
        name="Signed bytes authorize a different execution context than the signer saw",
        fact_a="digest the signer hashed",
        fact_b="fields the contract actually executes",
        construction="Reuse, extend, or wrap a signature so nonce, chainid, verifyingContract, amount, or spender is not the executed one.",
        witness="executed fields != signed fields AND the call succeeds",
        monetize_kill="Spender drains under a signature meant for something else. Dies if the digest binds every executed field including chain and contract.",
        cues=(
            r"signature|eip.?712|permit|ecrecover|digest",
            r"signed.*(data|message|hash)|arbitrary data|ownerIndex",
        ),
        seams_hint=("signature", "privilege"),
    ),
    Family(
        fid="nft_custody_vs_right",
        name="Custody of a unique token diverges from the rental or borrow right that should control it",
        fact_a="ERC-721 / ERC-1155 owner",
        fact_b="rental / borrow / listing record",
        construction="During a callback or handler change, take the NFT while the listing still believes it is escrowed (or the reverse).",
        witness="nft.ownerOf(id) != escrow.record.owner AND rental/borrow still ACTIVE",
        monetize_kill="Keep the NFT and the payment stream. Dies if custody and the right update in one non-reentrant write.",
        cues=(
            r"erc721|erc1155|\bnft\b|tokenid|rental|seaport",
            r"onERC721Received|onERC1155Received|fallback handler",
        ),
        seams_hint=("nft", "callback"),
    ),
    Family(
        fid="amm_reserve_vs_claim",
        name="Pool reserves and LP claims disagree after a valid swap, mint, or hook",
        fact_a="reserve / tick / inventory",
        fact_b="LP shares / position accounting",
        construction="Swap, donate, or hook-write so reserves move without matching LP burns (or LP burns without reserve movement).",
        witness="reserveDelta and lpDelta have opposite economic sign AND both calls succeeded",
        monetize_kill="Drain reserves against stale LP math. Dies if every reserve write updates LP invariant in the same function.",
        cues=(
            r"\bamm\b|uniswap|pool|liquidity|tick|lp token|hook",
            r"reserve|k\s*constant|invariant.*(pool|amm)",
        ),
        seams_hint=("amm",),
    ),
    Family(
        fid="borrow_vs_collateral",
        name="Debt exists without the collateral the solvency check used, or collateral is seized without debt closing",
        fact_a="debt share / borrowed amount",
        fact_b="collateral posted / seized",
        construction="Borrow, lever, or liquidate along a path that updates one side of health and not the other.",
        witness="debt > 0 AND collateral backing that debt == 0 (or collateral seized AND debt unchanged)",
        monetize_kill="Bad debt socialized, or seized collateral kept while debt remains. Dies if health is re-checked after both writes.",
        cues=(
            r"borrow|liquida|collateral factor|\bltv\b|debt token|health factor",
            r"undercollateral|bad debt|seize",
        ),
        seams_hint=("lending", "oracle"),
    ),
    Family(
        fid="rounding_conservation",
        name="Rounding direction on a conservation-neutral action creates or destroys value",
        fact_a="amount in (deposited, burned, paid)",
        fact_b="amount out (minted, released, received)",
        construction="Repeat a tiny action, or take a path that always rounds in the actor's favor, until claims exceed backing.",
        witness="sum(out) > sum(in) by more than dust across the sequence AND each call succeeded",
        monetize_kill="Accumulate the dust into extractable size. Dies if rounding favors the protocol on every value-out.",
        cues=(
            r"round(ing|s|ed)|precision|off.?by.?one|truncat",
            r"always rounds? (down|up)|favor(s|ing) the (user|attacker)",
        ),
        seams_hint=("accounting", "vault"),
    ),
    Family(
        fid="cap_or_bound",
        name="A documented cap, floor, or uniqueness bound is not the bound the write path honors",
        fact_a="documented / stored cap or unique id",
        fact_b="actual minted, withdrawn, or accepted amount",
        construction="Mint, withdraw, or register past the cap, or reuse an id the spec says is unique.",
        witness="writtenAmount > cap (or duplicate id accepted) AND call success",
        monetize_kill="Over-mint or double-register. Dies if the write checks the same cap it increments, atomically.",
        cues=(
            r"\bcap\b|max (amount|supply|deposit)|limit.*(exceed|bypass)",
            r"duplicate (id|order|key)|uniqueness",
        ),
        seams_hint=("accounting", "privilege"),
    ),
    Family(
        fid="time_lock_bypass",
        name="A time lock, cooldown, or expiry is true in storage and false at the write",
        fact_a="stored unlock time / expiry / cooldown",
        fact_b="write that still moves value",
        construction="Call before unlock, after expiry, or by changing the clock source the check does not read.",
        witness="block.timestamp < unlockTime AND withdraw succeeded (or expired==true AND settle succeeded)",
        monetize_kill="Early exit or stale right. Dies if every write uses the same clock and inclusive bound.",
        cues=(
            r"timelock|cool.?down|expiry|expired|delay.*(bypass|skip)",
            r"before (unlock|maturity)|after expiry",
        ),
        seams_hint=("payments", "privilege"),
    ),
    Family(
        fid="gas_prepaid_vs_settle",
        name="Prepaid execution credit and actual settlement charge disagree, moving value",
        fact_a="deposited / prepaid gas or fee credit",
        fact_b="amount actually charged or refunded at settle",
        construction="Force a remote call, fallback, or retry so the credit is over-refunded or under-charged until custody drains.",
        witness="refunded > prepaid - actualCost AND custody fell (or charge skipped AND call succeeded)",
        monetize_kill="Drain the gas tank or make peers pay. Dies if charge uses a measured cost bounded by the prepaid amount.",
        cues=(
            r"depositedgas|gasremaining|gasleft|min_fallback_reserve|execution gas",
            r"overpay.*gas|refund.*gas|prepaid",
        ),
        seams_hint=("bridge", "payments"),
    ),
    Family(
        fid="storage_slot_collision",
        name="Two representations share a storage slot and a valid write to one silently edits the other",
        fact_a="declared variable A",
        fact_b="declared variable B occupying the same slot",
        construction="Upgrade, inherit, or pack incorrectly so a permissionless or weakly gated write to A edits B's meaning.",
        witness="write(A) changed B's decoded value AND a value-moving call used B",
        monetize_kill="B is an owner, rate, or spent-id. Dies if slots are unique and the upgrade layout is append-only.",
        cues=(
            r"storage (collision|layout|slot)|gap\[|same slot",
            r"upgrade.*(overwrite|clobber)|packed struct",
        ),
        seams_hint=("privilege", "accounting"),
    ),
    Family(
        fid="fallback_generic",
        name="Two representations of the same fact can diverge while every individual function returns success",
        fact_a="the protocol's recorded fact",
        fact_b="the transferable or redeemable fact",
        construction="Sequence valid user actions on this seam until two components disagree about the same fact.",
        witness="reprA != reprB AND last call success",
        monetize_kill="Settle against the more favorable representation. Dies if a conservation identity is checked at the seam.",
        cues=(),
        seams_hint=("accounting",),
    ),
)


FALLBACK_FAMILY = FAMILIES[-1]
